import prettier from '@yap/eslint-config/prettier';
// Generated by the @nuxt/eslint module (run `nuxt prepare` if missing).
// Nuxt brings its own JS/TS/Vue rules; we only append the shared Prettier layer.
import withNuxt from './.nuxt/eslint.config.mjs';

export default withNuxt(...prettier, {
  rules: {
    '@typescript-eslint/no-explicit-any': 'off',
  },
});
